version: '3.9'
services:
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-container-bilemo
        ports:
            -  "8000:80"
        volumes:
            -   ./app:/var/www/project
            -   ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            -   php8-service
            -   mysql-service
        networks:
            dev:

    php8-service:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php8-container-bilemo
        depends_on:
            -   mysql-service
        ports:
            -   "9000:9000"
        volumes:
            -   ./app:/var/www/project
            -   ./php/conf.d/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        networks:
            dev:

    mysql-service:
        platform: linux/x86_64
        image: mysql:latest
        container_name: mysql-container-bilemo
        restart: always
        ports:
        -   "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: secret
        networks:
            dev:
        volumes:
            -   ./mysql:/var/lib/mysql

networks:
    dev:

volumes:
    db-data: